[host]
  preset_name = "ry3"
  host_name = "ry3"
  state_version = "26.05"

[user]
  name = "ry3"
  initialPassword = "123456"
  description = "l41twz <253585242+l41twz@users.noreply.github.com>"

[locale]
  timezone = "America/Sao_Paulo"
  default_locale = "en_US.UTF-8"
  lc_address = "pt_BR.UTF-8"
  lc_identification = "pt_BR.UTF-8"
  lc_measurement = "pt_BR.UTF-8"
  lc_monetary = "pt_BR.UTF-8"
  lc_name = "pt_BR.UTF-8"
  lc_numeric = "pt_BR.UTF-8"
  lc_paper = "pt_BR.UTF-8"
  lc_telephone = "pt_BR.UTF-8"
  lc_time = "pt_BR.UTF-8"
  keymap = "br-abnt2"

[modules]
  active = ["apps/fish-shell", "services/firewall-ports", "services/ollama-ai-amd", "system/gaming-sysctl", "system/systemd-boot", "apps/obsidian-khoj", "system/systemd-tweaks", "services/ssh-server", "apps/noctalia-mango", "hardware/pipewire-audio", "apps/pods", "hardware/cpu-amd", "services/docker-engine", "system/ssh-agent-git", "system/udev-rules", "apps/obsidian", "system/kernel-xanmod", "overlays/allow-unfree", "system/zram-swap", "apps/plasma6-desktop", "services/khoj", "hardware/bluetooth", "hardware/gpu-amd", "apps/cli-utils", "apps/zen-browser", "system/wayland-base", "system/nix-extra-options", "system/systemd-optimize", "system/nerd-fonts", "apps/dev-tools", "hardware/keyboard-layout-xkb-ptbr", "apps/mission-center", "apps/git-config", "apps/wave-terminal", "overlays/kde-overlay"]

[metadata]
  created_at = "2026-02-28T20:41:24Z"
  last_modified = "2026-03-10T17:44:39Z"
  last_applied_flake = "ry3-20260310-144439.nix"
