[host]
  preset_name = "ry3"
  host_name = "ry3"
  state_version = "26.05"

[user]
  name = "ry3"
  initialPassword = "123456"
  description = "l41twz <253585242+l41twz@users.noreply.github.com>"

[locale]
  timezone = "America/Sao_Paulo"
  default_locale = "en_US.UTF-8"
  lc_address = "pt_BR.UTF-8"
  lc_identification = "pt_BR.UTF-8"
  lc_measurement = "pt_BR.UTF-8"
  lc_monetary = "pt_BR.UTF-8"
  lc_name = "pt_BR.UTF-8"
  lc_numeric = "pt_BR.UTF-8"
  lc_paper = "pt_BR.UTF-8"
  lc_telephone = "pt_BR.UTF-8"
  lc_time = "pt_BR.UTF-8"
  keymap = "br-abnt2"

[modules]
  active = ["hardware/keyboard-layout-xkb-ptbr", "system/systemd-optimize", "system/udev-rules", "apps/fish-shell", "system/systemd-boot", "apps/pods", "system/gaming-sysctl", "apps/wave-terminal", "apps/mission-center", "overlays/kde-overlay", "hardware/cpu-amd", "apps/obsidian-khoj", "system/ssh-agent-git", "apps/cli-utils", "services/ollama-ai-amd", "hardware/pipewire-audio", "apps/plasma6-desktop", "apps/noctalia-shell", "system/kernel-xanmod", "system/nerd-fonts", "apps/mangowc-compositor", "system/systemd-tweaks", "services/khoj", "system/nix-extra-options", "apps/git-config", "apps/zen-browser", "services/firewall-ports", "system/wayland-base", "system/zram-swap", "hardware/gpu-amd", "apps/obsidian", "hardware/bluetooth", "overlays/allow-unfree", "apps/dev-tools", "services/ssh-server", "services/docker-engine"]

[metadata]
  created_at = "2026-02-28T20:41:24Z"
  last_modified = "2026-03-09T19:17:43Z"
  last_applied_flake = "ry3-20260309-161743.nix"
