[host]
  preset_name = "ry3"
  host_name = "ry3"
  state_version = "26.05"

[user]
  name = "ry3"
  initialPassword = "123456"
  description = "l41twz <253585242+l41twz@users.noreply.github.com>"

[locale]
  timezone = "America/Sao_Paulo"
  default_locale = "en_US.UTF-8"
  lc_address = "pt_BR.UTF-8"
  lc_identification = "pt_BR.UTF-8"
  lc_measurement = "pt_BR.UTF-8"
  lc_monetary = "pt_BR.UTF-8"
  lc_name = "pt_BR.UTF-8"
  lc_numeric = "pt_BR.UTF-8"
  lc_paper = "pt_BR.UTF-8"
  lc_telephone = "pt_BR.UTF-8"
  lc_time = "pt_BR.UTF-8"
  keymap = "br-abnt2"

[modules]
  active = ["apps/mission-center", "apps/cli-utils", "services/ssh-server", "system/nix-extra-options", "system/udev-rules", "apps/git-config", "apps/fish-shell", "apps/zen-browser", "overlays/kde-overlay", "system/wayland-base", "system/zram-swap", "hardware/gpu-amd", "services/ollama-ai-amd", "system/systemd-boot", "hardware/pipewire-audio", "services/firewall-ports", "system/kernel-xanmod", "hardware/cpu-amd", "system/nerd-fonts", "hardware/bluetooth", "services/docker-engine", "apps/obsidian", "apps/pods", "system/gaming-sysctl", "overlays/allow-unfree", "system/systemd-tweaks", "services/khoj", "apps/dev-tools", "hardware/keyboard-layout-xkb-ptbr", "apps/plasma6-desktop", "system/systemd-optimize", "apps/obsidian-khoj", "system/ssh-agent-git"]

[metadata]
  created_at = "2026-02-28T20:41:24Z"
  last_modified = "2026-03-06T20:42:25Z"
  last_applied_flake = "ry3-20260306-174225.nix"
