[host]
  preset_name = "ry5"
  host_name = "ry5"
  state_version = "26.05"

[user]
  name = "l41twz"
  initialPassword = "123456"
  description = "l41twz <253585242+l41twz@users.noreply.github.com>"

[locale]
  timezone = "America/Sao_Paulo"
  default_locale = "en_US.UTF-8"
  lc_address = "pt_BR.UTF-8"
  lc_identification = "pt_BR.UTF-8"
  lc_measurement = "pt_BR.UTF-8"
  lc_monetary = "pt_BR.UTF-8"
  lc_name = "pt_BR.UTF-8"
  lc_numeric = "pt_BR.UTF-8"
  lc_paper = "pt_BR.UTF-8"
  lc_telephone = "pt_BR.UTF-8"
  lc_time = "pt_BR.UTF-8"
  keymap = "br-abnt2"

[modules]
  active = ["apps/obsidian", "hardware/keyboard-layout-xkb-ptbr", "system/zram-swap", "system/nix-extra-options", "system/kernel-cachyos", "system/systemd-boot", "hardware/gpu-nvidia-pascal", "hardware/bluetooth", "system/udev-rules", "apps/greetd", "system/ssh-agent-git", "system/systemd-optimize", "apps/dev-tools", "system/nerd-fonts", "services/speaches-stt-tts-nvidia", "apps/obsidian-khoj", "apps/cli-utils", "services/khoj", "overlays/allow-unfree", "hardware/pipewire-audio", "system/gaming-sysctl", "services/docker-engine", "apps/zed-editor", "apps/fish-shell", "apps/git-config-gnome", "system/systemd-tweaks", "hardware/corsair-ckb-next", "apps/noctalia-niri", "services/llama-cpp-qwen-server", "system/ssh-agent-git-ry5", "hardware/cpu-amd", "apps/mission-center", "apps/zen-browser", "apps/wave-terminal", "services/ssh-server", "system/wayland-base", "services/firewall-ports"]

[metadata]
  created_at = "2026-02-28T20:41:24Z"
  last_modified = "2026-03-16T20:06:25Z"
  last_applied_flake = "ry5-20260316-170625.nix"
