[host]
  preset_name = "ry5"
  host_name = "ry5"
  state_version = "26.05"

[user]
  name = "l41twz"
  initialPassword = "123456"
  description = "l41twz <253585242+l41twz@users.noreply.github.com>"

[locale]
  timezone = "America/Sao_Paulo"
  default_locale = "en_US.UTF-8"
  lc_address = "pt_BR.UTF-8"
  lc_identification = "pt_BR.UTF-8"
  lc_measurement = "pt_BR.UTF-8"
  lc_monetary = "pt_BR.UTF-8"
  lc_name = "pt_BR.UTF-8"
  lc_numeric = "pt_BR.UTF-8"
  lc_paper = "pt_BR.UTF-8"
  lc_telephone = "pt_BR.UTF-8"
  lc_time = "pt_BR.UTF-8"
  keymap = "br-abnt2"

[modules]
  active = ["hardware/bluetooth", "apps/greetd", "hardware/gpu-nvidia-pascal", "services/ollama-ai-nvidia", "hardware/pipewire-audio", "apps/mission-center", "hardware/cpu-amd", "system/systemd-optimize", "services/khoj", "services/ssh-server", "services/docker-engine", "system/udev-rules", "apps/obsidian-khoj", "system/wayland-base", "hardware/keyboard-layout-xkb-ptbr", "apps/fish-shell", "apps/cli-utils", "system/nix-extra-options", "apps/nemo-filemanager", "system/zram-swap", "apps/git-config-gnome", "overlays/allow-unfree", "system/kernel-cachyos", "apps/wave-terminal", "apps/noctalia-niri", "hardware/corsair-ckb-next", "system/systemd-tweaks", "apps/dev-tools", "apps/obsidian", "apps/zen-browser", "system/systemd-boot", "system/nerd-fonts", "services/firewall-ports", "system/gaming-sysctl"]

[metadata]
  created_at = "2026-02-28T20:41:24Z"
  last_modified = "2026-03-10T18:20:32Z"
  last_applied_flake = "ry3-20260309-161743.nix"
