[host]
  preset_name = "ry5"
  host_name = "ry5"
  state_version = "26.05"

[user]
  name = "l41twz"
  initialPassword = "123456"
  description = "l41twz <253585242+l41twz@users.noreply.github.com>"

[locale]
  timezone = "America/Sao_Paulo"
  default_locale = "en_US.UTF-8"
  lc_address = "pt_BR.UTF-8"
  lc_identification = "pt_BR.UTF-8"
  lc_measurement = "pt_BR.UTF-8"
  lc_monetary = "pt_BR.UTF-8"
  lc_name = "pt_BR.UTF-8"
  lc_numeric = "pt_BR.UTF-8"
  lc_paper = "pt_BR.UTF-8"
  lc_telephone = "pt_BR.UTF-8"
  lc_time = "pt_BR.UTF-8"
  keymap = "br-abnt2"

[modules]
  active = ["system/zram-swap", "system/ssh-agent-git", "apps/fish-shell", "apps/obsidian", "hardware/corsair-ckb-next", "system/nix-extra-options", "apps/zen-browser", "system/gaming-sysctl", "system/udev-rules", "apps/wave-terminal", "services/ssh-server", "system/kernel-cachyos", "hardware/pipewire-audio", "overlays/allow-unfree", "services/docker-engine", "services/ollama-ai-nvidia", "services/khoj", "system/systemd-boot", "apps/obsidian-khoj", "apps/git-config-gnome", "apps/greetd", "apps/dev-tools", "apps/noctalia-niri", "system/wayland-base", "hardware/gpu-nvidia-pascal", "system/systemd-tweaks", "system/systemd-optimize", "apps/cli-utils", "hardware/keyboard-layout-xkb-ptbr", "hardware/bluetooth", "hardware/cpu-amd", "system/ssh-agent-git-ry5", "apps/mission-center", "services/firewall-ports", "system/nerd-fonts"]

[metadata]
  created_at = "2026-02-28T20:41:24Z"
  last_modified = "2026-03-12T19:41:36Z"
  last_applied_flake = "ry5-20260312-164136.nix"
